local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>th', builtin.help_tags, { desc = "telescope: help tags" })
vim.keymap.set('n', '<leader>tc', builtin.commands, { desc = "telescope: commands" })
vim.keymap.set('n', '<leader>tb', builtin.buffers, { desc = "telescope: buffers" })
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = "telescope: find files" })
vim.keymap.set('n', '<leader>pg', builtin.git_files, { desc = "telescope: git files" })
vim.keymap.set('n', '<leader>pr', builtin.live_grep, { desc = "telescope: live grep" })
vim.keymap.set('n', '<leader>tk', builtin.keymaps, { desc = "telescope: keymaps" })
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "telescope: grep" })
